import 'package:flutter/material.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:google_sign_in/google_sign_in.dart';
import '../../constansts/constants.dart';
import '../registration/racheeta_rules_screen.dart';
import 'JobSeeker_OTP_vericfication.dart';

class JobSeekerSignupScreen extends StatelessWidget {
  final TextEditingController _phoneController = TextEditingController();
  String _verificationId = "";
  // void submitJobSeekerProfile() async {
  //   if (_formKey.currentState!.validate()) {
  //     JobSeeker newJobSeeker = JobSeeker(
  //       jobSeekerId: 1,  // This would typically be auto-generated by your backend.
  //       fullName: fullNameController.text,
  //       phoneNumber: int.parse(phoneNumberController.text),
  //       profileImage: _profileImage?.path,
  //       specialty: selectedSpecialty!,
  //       degree: selectedDegree!,
  //       degreeImage: _degreeImage?.path,
  //       address: addressController.text,
  //       email: emailController.text,
  //       password: 'hashed_password_here',
  //       gpsLocation: 'gps_coordinates_here',  // You can collect GPS data using the location package.
  //       createdAt: DateTime.now(),
  //       updatedAt: DateTime.now(),
  //     );
  //
  //     // Example HTTP request to send the profile data to the backend
  //     final response = await http.post(
  //       Uri.parse('https://your-api-url.com/jobseeker/create'),
  //       headers: <String, String>{
  //         'Content-Type': 'application/json; charset=UTF-8',
  //       },
  //       body: jsonEncode(newJobSeeker.toJson()),
  //     );
  //
  //     if (response.statusCode == 201) {
  //       // Successfully submitted
  //       print('Profile submitted!');
  //     } else {
  //       // Error occurred
  //       print('Failed to submit profile');
  //     }
  //   }
  // }

  bool isValidPhoneNumber(String number) {
    RegExp regex = RegExp(r'^\+964\d{10}$'); // Adjust the regex as needed
    return regex.hasMatch(number);
  }

  // Phone Verification Logic
  void verifyPhoneNumber(BuildContext context, String phoneNumber) {
    FirebaseAuth.instance.verifyPhoneNumber(
      phoneNumber: phoneNumber,
      verificationCompleted: (PhoneAuthCredential credential) async {
        // Optionally handle auto sign-in if Firebase automatically verifies the number
      },
      verificationFailed: (FirebaseAuthException e) {
        ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(content: Text("فشل التحقق من الرقم: ${e.message}")));
      },
      codeSent: (String verificationId, int? resendToken) {
        _verificationId = verificationId;
        Navigator.push(
          context,
          MaterialPageRoute(
            builder: (context) => JobSeekerOTPVerificationPage(
              verificationId: verificationId,
            ),
          ),
        );
      },
      codeAutoRetrievalTimeout: (String verificationId) {},
    );
  }

  // Google Sign-In Logic
  Future<void> signInWithGoogle(BuildContext context) async {
    try {
      final GoogleSignInAccount? googleUser = await GoogleSignIn().signIn();
      if (googleUser == null) {
        // The user canceled the sign-in
        return;
      }

      final GoogleSignInAuthentication googleAuth =
          await googleUser.authentication;
      final OAuthCredential credential = GoogleAuthProvider.credential(
        accessToken: googleAuth.accessToken,
        idToken: googleAuth.idToken,
      );

      await FirebaseAuth.instance.signInWithCredential(credential);
      ScaffoldMessenger.of(context).showSnackBar(const SnackBar(
          content: Text("تم تسجيل الدخول بنجاح باستخدام Google")));
    } catch (e) {
      ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text("فشل تسجيل الدخول باستخدام Google: $e")));
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text(
          'إنشاء حساب أو سجل الدخول',
          style: kAppBarTextStyle,
        ),
        centerTitle: true,
        backgroundColor: Colors.white,
        elevation: 0,
        leading: IconButton(
          icon: const Icon(Icons.close, color: Colors.blue),
          onPressed: () => Navigator.of(context).pop(),
        ),
      ),
      body: SingleChildScrollView(
        child: Padding(
          padding: const EdgeInsets.all(16.0),
          child: Column(
            children: [
              const Text(
                'تستطيع الاستمرار عبر',
                textAlign: TextAlign.center,
                style: kFieldsTextStyle,
              ),
              const SizedBox(height: 20),

              // Phone Number Field
              TextField(
                textAlign: TextAlign.right,
                controller: _phoneController,
                decoration: const InputDecoration(
                  prefixIcon: Icon(Icons.phone),
                  labelText: 'رقم المحمول',
                  alignLabelWithHint: true,
                  prefixText: '+964 ',
                  border: OutlineInputBorder(),
                  contentPadding: EdgeInsets.fromLTRB(12, 16, 16, 16),
                ),
              ),
              const SizedBox(
                height: 20,
              ),
              ElevatedButton(
                onPressed: () {
                  String phoneNumber = "+964" + _phoneController.text;
                  if (isValidPhoneNumber(phoneNumber)) {
                    verifyPhoneNumber(context, phoneNumber);
                  } else {
                    ScaffoldMessenger.of(context).showSnackBar(
                        const SnackBar(content: Text("قم بادخال رقم الهاتف")));
                  }
                },
                child: const Text("اضغط هنا للتسجيل"),
              ),
              const SizedBox(height: 20),
              ElevatedButton.icon(
                onPressed: () => signInWithGoogle(context),
                style: ElevatedButton.styleFrom(
                  minimumSize: Size(double.infinity, 50),
                  backgroundColor: Colors.red, // Google button color
                ),
                icon: Icon(Icons.g_translate, color: Colors.white),
                label: const Text(
                  "تسجيل ب Google",
                  style: TextStyle(color: Colors.white),
                ),
              ),
              SizedBox(height: 20),
              InkWell(
                onTap: () {
                  // Navigate to Racheeta Rules page
                  Navigator.push(
                    context,
                    MaterialPageRoute(
                      builder: (context) => RacheetaRulesPage(),
                    ),
                  );
                },
                child: const Text(
                  'بالضغط فانت توافق على شروط واحكام تطبيق راجيته',
                  textAlign: TextAlign.center,
                  style: TextStyle(color: Colors.blue),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
