import 'package:intl/date_symbols.dart';

final DateSymbols arabicIraqiSymbols = DateSymbols(
  NAME: "ar_IQ_traditional",
  ERAS: const ["ق.م", "م"],
  ERANAMES: const ["قبل الميلاد", "ميلادي"],
  NARROWMONTHS: const [
    "١",
    "٢",
    "٣",
    "٤",
    "٥",
    "٦",
    "٧",
    "٨",
    "٩",
    "١٠",
    "١١",
    "١٢"
  ],
  MONTHS: const [
    "كانون الثاني",
    "شباط",
    "آذار",
    "نيسان",
    "أيار",
    "حزيران",
    "تموز",
    "آب",
    "أيلول",
    "تشرين الأول",
    "تشرين الثاني",
    "كانون الأول"
  ],
  STANDALONEMONTHS: const [
    "كانون الثاني",
    "شباط",
    "آذار",
    "نيسان",
    "أيار",
    "حزيران",
    "تموز",
    "آب",
    "أيلول",
    "تشرين الأول",
    "تشرين الثاني",
    "كانون الأول"
  ],
  SHORTMONTHS: const [
    "كانون ٢",
    "شباط",
    "آذار",
    "نيسان",
    "أيار",
    "حزيران",
    "تموز",
    "آب",
    "أيلول",
    "تشرين ١",
    "تشرين ٢",
    "كانون ١"
  ],
  STANDALONESHORTMONTHS: const [
    "كانون ٢",
    "شباط",
    "آذار",
    "نيسان",
    "أيار",
    "حزيران",
    "تموز",
    "آب",
    "أيلول",
    "تشرين ١",
    "تشرين ٢",
    "كانون ١"
  ],
  STANDALONENARROWMONTHS: const [
    "١",
    "٢",
    "٣",
    "٤",
    "٥",
    "٦",
    "٧",
    "٨",
    "٩",
    "١٠",
    "١١",
    "١٢"
  ],
  WEEKDAYS: const [
    "الأحد",
    "الاثنين",
    "الثلاثاء",
    "الأربعاء",
    "الخميس",
    "الجمعة",
    "السبت"
  ],
  STANDALONEWEEKDAYS: const [
    "الأحد",
    "الاثنين",
    "الثلاثاء",
    "الأربعاء",
    "الخميس",
    "الجمعة",
    "السبت"
  ],
  SHORTWEEKDAYS: const ["أحد", "اثن", "ثلا", "أرب", "خمي", "جمع", "سبت"],
  STANDALONESHORTWEEKDAYS: const [
    "أحد",
    "اثن",
    "ثلا",
    "أرب",
    "خمي",
    "جمع",
    "سبت"
  ],
  NARROWWEEKDAYS: const ["ح", "ن", "ث", "أ", "خ", "ج", "س"],
  STANDALONENARROWWEEKDAYS: const ["ح", "ن", "ث", "أ", "خ", "ج", "س"],
  FIRSTDAYOFWEEK: 6,
  WEEKENDRANGE: const [5, 6],
  FIRSTWEEKCUTOFFDAY: 5,
  QUARTERS: const [
    "الربع الأول",
    "الربع الثاني",
    "الربع الثالث",
    "الربع الرابع"
  ],
  SHORTQUARTERS: const ["ر1", "ر2", "ر3", "ر4"],
  AMPMS: const ["ص", "م"],
  DATEFORMATS: const ["EEEE، d MMMM y", "d MMMM y", "dd/MM/y", "dd/MM/yy"],
  TIMEFORMATS: const ["h:mm:ss a zzzz", "h:mm:ss a z", "h:mm:ss a", "h:mm a"],
  DATETIMEFORMATS: const ["{1} {0}", "{1} 'في' {0}", "{1}, {0}", "{1}, {0}"],
);
