import 'package:racheeta/models/hsp_models/pharmacist_model.dart';
import 'package:racheeta/models/hsp_models/therapist_model.dart';

import 'beauty_center_model.dart';
import 'hospital_model.dart';
import 'laboratory_model.dart';
import 'medical_center_model.dart';
import 'nurse_models.dart';

List<BeautyCenter> beautyCenters = [
  BeautyCenter(
    beautyCenterId: 1,
    userId: 101,
    centerName: 'Glow Beauty Clinic',
    bio: 'A center specialized in beauty and skincare.',
    address: 'Street 123, City X',
    availabilityTime: '9 AM - 6 PM',
    gpsLocation: '123.456, 789.123',
    advertise: true,
    advertisePrice: 100.0,
    advertiseDuration: '30 days',
    profileImage: 'assets/images/beauty_center_1.png',
    phoneNumber: 123456789,
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  BeautyCenter(
    beautyCenterId: 2,
    userId: 102,
    centerName: 'Elegance Aesthetics',
    bio: 'A luxury beauty clinic.',
    address: 'Street 456, City Y',
    availabilityTime: '10 AM - 8 PM',
    gpsLocation: '456.789, 987.654',
    advertise: false,
    profileImage: 'assets/images/beauty_center_2.png',
    phoneNumber: 987654321,
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  BeautyCenter(
    beautyCenterId: 3,
    userId: 103,
    centerName: 'Royal Beauty Spa',
    bio: 'Professional beauty and spa services.',
    address: 'Street 789, City Z',
    availabilityTime: '10 AM - 5 PM',
    gpsLocation: '789.123, 123.456',
    advertise: true,
    advertisePrice: 200.0,
    advertiseDuration: '45 days',
    profileImage: 'assets/images/beauty_center_3.png',
    phoneNumber: 456789123,
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
];
List<Pharmacist> pharmacists = [
  Pharmacist(
    pharmacistId: 1,
    userId: 301,
    pharmacyName: 'Healthy Life Pharmacy',
    address: 'Street 123, City X',
    bio: 'Pharmacy open 24/7.',
    availabilityTime: '24 hours',
    gpsLocation: '123.456, 789.123',
    onDutyPharmacy: true,
    advertise: true,
    advertisePrice: 50.0,
    advertiseDuration: '30 days',
    profileImage: 'assets/images/pharmacy_1.png',
    phoneNumber: 123456789,
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  Pharmacist(
    pharmacistId: 2,
    userId: 302,
    pharmacyName: 'Care Plus Pharmacy',
    address: 'Street 456, City Y',
    bio: 'Best service with home delivery.',
    availabilityTime: '8 AM - 10 PM',
    gpsLocation: '456.789, 987.654',
    onDutyPharmacy: false,
    advertise: false,
    profileImage: 'assets/images/pharmacy_2.png',
    phoneNumber: 987654321,
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  Pharmacist(
    pharmacistId: 3,
    userId: 303,
    pharmacyName: 'MediHelp Pharmacy',
    address: 'Street 789, City Z',
    bio: '24/7 home delivery pharmacy.',
    availabilityTime: '24 hours',
    gpsLocation: '789.123, 123.456',
    onDutyPharmacy: true,
    advertise: true,
    advertisePrice: 75.0,
    advertiseDuration: '15 days',
    profileImage: 'assets/images/pharmacy_3.png',
    phoneNumber: 456789123,
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
];
List<Hospital> hospitals = [
  Hospital(
    hospitalId: 1,
    userId: 401,
    hospitalName: 'General Hospital X',
    specialty: 'General Medicine',
    administration: 'Dr. John Smith',
    bio: 'Comprehensive medical services.',
    address: 'Street 123, City X',
    availabilityTime: '24 hours',
    gpsLocation: '123.456, 789.123',
    advertise: true,
    advertisePrice: 200.0,
    advertiseDuration: '30 days',
    profileImage: 'assets/icons/hospital1.png',
    phoneNumber: 123456789,
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  Hospital(
    hospitalId: 2,
    userId: 402,
    hospitalName: 'Specialty Clinic Y',
    specialty: 'Cardiology',
    administration: 'Dr. Jane Doe',
    bio: 'Heart and vascular services.',
    address: 'Street 456, City Y',
    availabilityTime: '8 AM - 6 PM',
    gpsLocation: '456.789, 987.654',
    advertise: false,
    profileImage: 'assets/icons/hospital1.png',
    phoneNumber: 987654321,
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  Hospital(
    hospitalId: 3,
    userId: 403,
    hospitalName: 'Neuro Center Z',
    specialty: 'Neurology',
    administration: 'Dr. Alice Lee',
    bio: 'Advanced treatment for nervous system disorders.',
    address: 'Street 789, City Z',
    availabilityTime: '9 AM - 5 PM',
    gpsLocation: '789.123, 123.456',
    advertise: true,
    advertisePrice: 250.0,
    advertiseDuration: '45 days',
    profileImage: 'assets/icons/hospital1.png',
    phoneNumber: 456789123,
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
];
List<Laboratory> laboratories = [
  Laboratory(
    laboratoryId: 1,
    userId: 501,
    laboratoryName: 'LabOne Diagnostics',
    availableTests: 'Blood Test, X-Ray, MRI',
    bio: 'Advanced diagnostic services.',
    address: 'Street 123, City X',
    availabilityTime: '9 AM - 9 PM',
    gpsLocation: '123.456, 789.123',
    advertise: true,
    advertisePrice: 100.0,
    advertiseDuration: '30 days',
    profileImage: 'assets/images/lab_1.png',
    phoneNumber: 123456789,
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  Laboratory(
    laboratoryId: 2,
    userId: 502,
    laboratoryName: 'HealthTech Labs',
    availableTests: 'Blood Test, Ultrasound',
    bio: 'Affordable lab services.',
    address: 'Street 456, City Y',
    availabilityTime: '8 AM - 6 PM',
    gpsLocation: '456.789, 987.654',
    advertise: false,
    profileImage: 'assets/images/lab_2.png',
    phoneNumber: 987654321,
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  Laboratory(
    laboratoryId: 3,
    userId: 503,
    laboratoryName: 'CityScan Diagnostics',
    availableTests: 'CT Scan, MRI',
    bio: 'Specializing in imaging and diagnostics.',
    address: 'Street 789, City Z',
    availabilityTime: '10 AM - 7 PM',
    gpsLocation: '789.123, 123.456',
    advertise: true,
    advertisePrice: 150.0,
    advertiseDuration: '45 days',
    profileImage: 'assets/images/lab_3.png',
    phoneNumber: 456789123,
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
];
List<MedicalCenter> medicalCenters = [
  MedicalCenter(
    centerId: 1,
    userId: 601,
    centerName: 'CarePlus Medical Center',
    directorName: 'Dr. John Doe',
    bio: 'Comprehensive medical care for families.',
    address: 'Street 123, City X',
    availabilityTime: '8 AM - 8 PM',
    gpsLocation: '123.456, 789.123',
    advertise: true,
    advertisePrice: 120.0,
    advertiseDuration: '30 days',
    profileImage: 'assets/images/medical_center_1.png',
    phoneNumber: 123456789,
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  MedicalCenter(
    centerId: 2,
    userId: 602,
    centerName: 'HealthFirst Clinic',
    directorName: 'Dr. Jane Smith',
    bio: 'Providing top-notch healthcare services.',
    address: 'Street 456, City Y',
    availabilityTime: '9 AM - 5 PM',
    gpsLocation: '456.789, 987.654',
    advertise: false,
    profileImage: 'assets/images/medical_center_2.png',
    phoneNumber: 987654321,
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  MedicalCenter(
    centerId: 3,
    userId: 603,
    centerName: 'WellnessCare Clinic',
    directorName: 'Dr. Alice Lee',
    bio: 'Personalized medical care and wellness programs.',
    address: 'Street 789, City Z',
    availabilityTime: '8 AM - 4 PM',
    gpsLocation: '789.123, 123.456',
    advertise: true,
    advertisePrice: 200.0,
    advertiseDuration: '45 days',
    profileImage: 'assets/images/medical_center_3.png',
    phoneNumber: 456789123,
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
];
List<Nurse> nurses = [
  Nurse(
      nurseId: 1,
      userId: 701,
      name: 'Nurse Emily Williams',
      specialty: 'Pediatrics',
      bio: 'Expert in pediatric care with home visits.',
      degree: 'BSN',
      address: 'Street 123, City X',
      availabilityTime: '9 AM - 3 PM',
      advertise: true,
      advertisePrice: 80.0,
      advertiseDuration: '30 days',
      profileImage: 'assets/images/nurse_1.png',
      phoneNumber: 123456789,
      homeVisit: true,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
      gpsLocation: ''),
  Nurse(
    nurseId: 2,
    userId: 702,
    name: 'Nurse Sarah Johnson',
    specialty: 'Geriatrics',
    bio: 'Specialized in elderly care and support.',
    degree: 'MSN',
    address: 'Street 456, City Y',
    availabilityTime: '10 AM - 6 PM',
    advertise: false,
    profileImage: 'assets/images/nurse_2.png',
    phoneNumber: 987654321,
    homeVisit: false,
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
    gpsLocation: '',
  ),
  Nurse(
      nurseId: 3,
      userId: 703,
      name: 'Nurse David Miller',
      specialty: 'Home Care',
      bio: 'Experienced in home health services.',
      degree: 'RN',
      address: 'Street 789, City Z',
      availabilityTime: '8 AM - 4 PM',
      advertise: true,
      advertisePrice: 100.0,
      advertiseDuration: '45 days',
      profileImage: 'assets/images/nurse_3.png',
      phoneNumber: 456789123,
      homeVisit: true,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
      gpsLocation: ''),
];
List<Therapist> therapists = [
  Therapist(
    therapistId: 1,
    userId: 801,
    name: 'Therapist John Adams',
    degree: 'MPT',
    bio: 'Specialized in physical therapy for sports injuries.',
    address: 'Street 123, City X',
    availabilityTime: '10 AM - 5 PM',
    advertise: true,
    advertisePrice: 90.0,
    advertiseDuration: '30 days',
    profileImage: 'assets/images/therapist_1.png',
    phoneNumber: 123456789,
    gpsLocation: '',
    homeVisit: false,
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  Therapist(
    therapistId: 2,
    userId: 802,
    name: 'Therapist Lisa Brown',
    degree: 'OTD',
    gpsLocation: '',
    bio: 'Expert in occupational therapy and rehabilitation.',
    address: 'Street 456, City Y',
    availabilityTime: '9 AM - 3 PM',
    advertise: false,
    profileImage: 'assets/images/therapist_2.png',
    phoneNumber: 987654321,
    homeVisit: true,
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  Therapist(
    therapistId: 3,
    userId: 803,
    gpsLocation: '',
    name: 'Therapist Michael Green',
    degree: 'PhD in Physical Therapy',
    bio: 'Providing advanced therapeutic services for chronic pain.',
    address: 'Street 789, City Z',
    availabilityTime: '8 AM - 4 PM',
    advertise: true,
    advertisePrice: 120.0,
    advertiseDuration: '60 days',
    profileImage: 'assets/images/therapist_3.png',
    phoneNumber: 456789123,
    homeVisit: false,
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
];
